/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pages/favorite" |
       "/pages/hi" |
       "/pages/home" |
       "/pages/login" |
       "/pages/orders" |
       "/pages/profile" |
       "/pages/reserve" |
       "/pages/merchant/m-comments" |
       "/pages/merchant/m-login" |
       "/pages/merchant/m-orders" |
       "/pages/merchant/m-publish" |
       "/pages/merchant/m-services";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
